# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from


# Settings
navigation:           true
headroom:             true
color:                '#268bd2'
exclude:              [CNAME, README.md, NOTES.md, .gitignore, js, sass, .gulpfile, node_modules]
sass:
  sass_dir:           _sass
  style:              compressed


# Site meta
title:                Lorenzo Gatti
tagline:              'Doctoral candidate in Computational Sciences and Phylogenomics'
keywords:             'molecular evolution, computer science, evolution, dynamics, phylogenomics, trees, computational biology, bioinformatics'
description:          'Doctoral candidate in computational sciences and phylogeneomics @ Zurich University of Applied Sciences, Wädenswil (CH)'
image:                /assets/lorenzo.jpg
logo:                 /assets/logo.png
url:                  http://lorenzogatti.me
baseurl:              ''

## replace analytics key below to enable tracking, leave blank to disable
google_analytics_key: UA-73302940-1

author:
  name:               Lorenzo Gatti
  url:                http://lorenzogatti.me
  email:              hello@lorenzogatti.me
  twitter:            lore_89

## outputs the social links in the sidebar, leave url blank to omit a social network, re-arrange to change order
social:
  ZHAW:               https://www.zhaw.ch/en/about-us/person/gati/
  ResearchGate:       https://www.researchgate.net/profile/Lorenzo_Gatti
  academica:          https://zhaw.academia.edu/LorenzoGatti
  twitter:            https://twitter.com/lore_89

version:              2.0.0

github:
  repo:               https://github.com/gattil


# /* Predefined theme colors */
# $red: #ac4142;
# $orange: #d28445;
# $yellow: #f4bf75;
# $green: #90a959;
# $cyan: #75b5aa;
# $blue: #268bd2;
# // $blue: #6a9fb5;
# $brown: #8f5536;

# /* Set your colors here. You can use the predefined colors from above. */
