# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from


# Settings
navigation:           true
headroom:             true
color:                '#268bd2'
exclude:              [CNAME, README.md, NOTES.md, .gitignore, js, sass, .gulpfile, node_modules]
sass:
  sass_dir:           _sass
  style:              compressed


# Site meta
title:                Dr. sc. nat.
name:                 Lorenzo Gatti
tagline:              'Cloud Engineer interested in high performance cloud computing, data analytics, and business intelligence'
keywords:             'cloud, data analytics, business intelligence, cloud computing, aws, hpc, high performance computing, molecular evolution, computer science, evolution, dynamics, phylogenomics, trees, computational biology, bioinformatics'
description:          'Cloud Engineer interested in high performance cloud computing, data analytics, and business intelligence'
image:                /assets/about/lorenzo3.jpg
logo:                 /assets/logo.png
url:                  https://lorenzogatti.me
baseurl:              ''

## replace analytics key below to enable tracking, leave blank to disable
google_analytics_key: UA-73302940-1

author:
  name:               Lorenzo Gatti
  url:                https://lorenzogatti.me
  email:              lg@lorenzogatti.me
  twitter:            lore_89

## outputs the social links in the sidebar, leave url blank to omit a social network, re-arrange to change order
social:
  LinkedIn:           https://www.linkedin.com/in/lorenzogatti
  twitter:            https://twitter.com/lore_89
  ResearchGate:       https://www.researchgate.net/profile/Lorenzo_Gatti
  academica:          https://uzh.academia.edu/LorenzoGatti


version:              2.0.0

github:
  repo:               https://github.com/gattil

bitbucket:
  repo:               https://bitbucket.com/lorenzogatti89/

jira:
  url:               https://devops.lorenzogatti.me/

# /* Predefined theme colors */
# $red: #ac4142;
# $orange: #d28445;
# $yellow: #f4bf75;
# $green: #90a959;
# $cyan: #75b5aa;
# $blue: #268bd2;
# // $blue: #6a9fb5;
# $brown: #8f5536;

# /* Set your colors here. You can use the predefined colors from above. */
